---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.59.0_Linux-64bit.deb
  - sudo rm hugo_0.59.0_Linux-64bit.deb
branches:
  only:
    - master
    - /.*/
# Testing if the site builds
script:
  - cd docs_source_files && hugo && cd ..
  - cd site_source_files && hugo && cd ..
deploy:
  - provider: script
    script: chmod +x $TRAVIS_BUILD_DIR/deploy.sh && $TRAVIS_BUILD_DIR/deploy.sh
    on:
      branch: master
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#selenium"
#    on_success: change
#    on_failure: always
#    template:
#      - "%{repository} (%{commit}): %{message}"
#      - "Build details: %{build_url}"
