[build]
publish = "website_and_docs/public"
command = "chmod +x build-site.sh && ./build-site.sh"

[context.production.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.deploy-preview.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"

[context.branch-deploy]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.branch-deploy.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"
