baseURL = "https://selenium.dev/documentation"
languageCode = "en-US"
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

canonifyurls = "true"

title = "Documentation for Selenium"
theme = "hugo-theme-learn"
copyright = "2013-{year}"

# Code highlighting
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "solarized-dark"

enableGitInfo = true

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "selenium"
  editURL = "https://github.com/SeleniumHQ/site/edit/master/docs_source_files/content/"
  ghrepo = "https://github.com/SeleniumHQ/site/"
  description = "Documentation for Selenium"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Selenium"
weight = 1
languageName = "English"
baseURL = "https://selenium.dev/documentation/en"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Report a bug"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> How to contribute"
url = "contributing"
weight = 30

[Languages.es]
title = "Documentación de Selenium"
weight = 2
languageName = "Español"
baseURL = "https://selenium.dev/documentation/es"

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo en GitHub"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Reportar un problema"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Créditos"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Cómo contribuír"
url = "contributing"
weight = 30

[Languages.nl]
title = "Selenium documentatie"
weight = 3
languageName = "Nederlands"
baseURL = "https://selenium.dev/documentation/nl"

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.nl.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Meld een probleem"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Hoe bij te dragen"
url = "contributing"
weight = 30

[Languages.zh-cn]
title = "Selenium 文档"
weight = 4
languageName = "中文简体"
baseURL = "https://selenium.dev/documentation/zh-cn"

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Report a bug"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> How to contribute"
url = "contributing"
weight = 30

[Languages.fr]
title = "Documentation Selenium"
weight = 5
languageName = "Français"
baseURL = "https://selenium.dev/documentation/fr"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Signaler un problème"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Crédits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Comment contribuer"
url = "contributing"
weight = 30

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[Languages.ja]
title = "Seleniumドキュメント"
weight = 6
languageName = "日本語"
baseURL = "https://selenium.dev/documentation/ja"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev/"
weight = 1

[[Languages.ja.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub リポ"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> バグ報告"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> クレジット"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 貢献方法"
url = "contributing"
weight = 30

[Languages.ko]
title = "Selenium 문서"
weight = 7
languageName = "한국어"
baseURL = "https://selenium.dev/documentation/ko"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium 홈"
url = "https://selenium.dev/"
weight = 1

[[Languages.ko.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> 버그 신고"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> 크레딧"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 기여하기"
url = "contributing"
weight = 30

[Languages.de]
title = "Dokumentation für Selenium"
weight = 1
languageName = "Deutsch"
baseURL = "https://selenium.dev/documentation/de"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-home'></i> Selenium Home"
url = "https://selenium.dev"
weight = 8

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/seleniumhq.github.io"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Fehler einmelden"
url = "https://github.com/seleniumhq/seleniumhq.github.io/issues"
weight = 11

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-trophy'></i> Impressum"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Wie kann ich beitragen?"
url = "contributing"
weight = 30
