baseURL = "/"
title = "Selenium"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true
#ignoreErrors = ["error-remote-getjson"] 
# Language settings
# contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:filename/"
# blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "Selenium"
description = "Selenium automates browsers. That's it!"
languageName ="English"
weight = 1
[languages.pt-br]
title = "Selenium"
description = "Selenium automates browsers. That's it!"
languageName ="Português (Brasileiro)"
weight = 2
[languages.zh-cn]
title = "Selenium"
description = "Selenium automates browsers. That's it!"
languageName = "中文简体"
weight = 3
[languages.ja]
title = "Selenium"
description = "Selenium automates browsers. That's it!"
languageName = "日本語"
weight = 4
[languages.other]
title = "Selenium"
description = "Selenium automates browsers. That's it!"
languageName ="Other"
weight = 5



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print"]

[params]
copyright = "Software Freedom Conservancy"
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
images = ["images/selenium_4_logo.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/SeleniumHQ/seleniumhq.github.io"
github_subdir = "website_and_docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/seleniumhq/selenium"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "trunk"

# Enable Lunr.js offline search
offlineSearch = false
offlineSearchMaxResults = 30

# Enable Algolia DocSearch
algolia_docsearch = true

# Enable Plausible.io
plausible_analytics = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Max amount of entries on the side bar
sidebar_menu_truncate = 80

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
# [params.ui.feedback]
# enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
# yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
# no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://groups.google.com/group/selenium-users"
	icon = "fas fa-mail-bulk"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Selenium in Twitter"
	url = "https://twitter.com/SeleniumHQ"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "SeleniumConf YouTube Channel"
	url = "https://www.youtube.com/channel/UCbDlgX_613xNMrDqCe3QNEw"
	icon = "fab fa-youtube"
        desc = "Check all the conference talks and learn from the community!"
[[params.links.user]]
	name = "Selenium in Facebook"
	url = "https://www.facebook.com/Selenium2.WebDriver"
	icon = "fab fa-facebook"
        desc = "Get news and updates in Facebook!"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "Software Freedom Conservancy"
	url = "mailto:selenium@sfconservancy.org"
	icon = "fas fa-envelope-square"
        desc = "Reach out to the SFC."
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/seleniumhq/selenium"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/seleniumhq/shared_invite/zt-vv33sc0w-VKKQop3WDV_lfrLXGGHvDw"
	icon = "fab fa-slack"
        desc = "Chat with other project developers and users in Slack"
[[params.links.developer]]
	name = "IRC"
	url = "https://kiwiirc.com/nextclient/irc.libera.chat/#selenium"
	icon = "fas fa-comments"
        desc = "Chat with other project developers and users in IRC"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://groups.google.com/g/selenium-developers"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"


[[menus.main]]
identifier = "About"
name = "About"
weight = 10

[[menus.main]]
name = "About Selenium"
parent = "About"
url = "/about"
weight = 1

[[menus.main]]
name = "Structure and Governance"
parent = "About"
url = "/project"
weight = 10

[[menus.main]]
name = "Events"
parent = "About"
url = "/events"
weight = 20

[[menus.main]]
name = "Ecosystem"
parent = "About"
url = "/ecosystem"
weight = 30

[[menus.main]]
name = "History"
parent = "About"
url = "/history"
weight = 40

[[menus.main]]
name = "Get Involved"
parent = "About"
url = "/getinvolved"
weight = 50

[[menus.main]]
name = "Sponsors"
parent = "About"
url = "/sponsors"
weight = 60

[[menus.main]]
identifier = "Downloads"
name = "Downloads"
url = "/downloads"
weight = 20

[[menus.main]]
identifier = "Projects"
name = "Projects"
url = "/projects"
weight = 30

[[menus.main]]
identifier = "Documentation"
name = "Documentation"
url = "/documentation"
weight = 30

[[menus.main]]
identifier = "Support"
name = "Support"
url = "/support"
weight = 50

[[menus.main]]
identifier = "Blog"
name = "Blog"
url = "/blog"
weight = 60

[taxonomies]
tag = "tags"
category = "categories"
year = "year"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_','^SELENIUM_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

