name: Publish Selenium Site

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    # Skip job based on the commit message
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
      - name: Build
        run: chmod +x build-site.sh && ./build-site.sh
        env:
          SELENIUM_CI_TOKEN: ${{secrets.SELENIUM_CI_TOKEN}}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.SELENIUM_CI_TOKEN }}
          publish_dir: ./site_source_files/public
          publish_branch: master
          user_name: 'Selenium CI Bot'
          user_email: 'selenium-ci@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          cname: www.selenium.dev
