name: Test site build

on:
  pull_request:
    branches:
      - dev

jobs:
  test_build:
    # Skip job based on the commit message
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
      - name: Build documentation site
        run: cd docs_source_files && hugo
        env:
          SELENIUM_CI_TOKEN: ${{secrets.SELENIUM_CI_TOKEN}}
      - name: Build website
        run: cd site_source_files && hugo
